"""
Django settings for NBNE Business Platform (Rev 3).

Generated by 'django-admin startproject' using Django 5.2.11.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config, Csv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default=config('DJANGO_SECRET_KEY', default='django-insecure-dev-key-change-in-production'))

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1', cast=Csv())


# Application definition

# --- Module feature flags ---------------------------------------------------
BOOKINGS_MODULE_ENABLED = config('BOOKINGS_MODULE_ENABLED', default=True, cast=bool)
PAYMENTS_MODULE_ENABLED = config('PAYMENTS_MODULE_ENABLED', default=True, cast=bool)
STAFF_MODULE_ENABLED = config('STAFF_MODULE_ENABLED', default=True, cast=bool)
COMMS_MODULE_ENABLED = config('COMMS_MODULE_ENABLED', default=True, cast=bool)
COMPLIANCE_MODULE_ENABLED = config('COMPLIANCE_MODULE_ENABLED', default=True, cast=bool)
DOCUMENTS_MODULE_ENABLED = config('DOCUMENTS_MODULE_ENABLED', default=True, cast=bool)
CRM_MODULE_ENABLED = config('CRM_MODULE_ENABLED', default=True, cast=bool)
TENANTS_MODULE_ENABLED = config('TENANTS_MODULE_ENABLED', default=True, cast=bool)

# --- Dashboard feature flags ------------------------------------------------
DASHBOARD_TODAY_V2 = config('DASHBOARD_TODAY_V2', default=True, cast=bool)

INSTALLED_APPS = [
    "jazzmin",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    # Core apps (always enabled)
    "core",
    "accounts",
    "auditlog",
]

# Custom user model
AUTH_USER_MODEL = 'accounts.User'

# Conditionally register optional modules
if TENANTS_MODULE_ENABLED:
    INSTALLED_APPS.append('tenants')
if BOOKINGS_MODULE_ENABLED:
    INSTALLED_APPS.append('bookings')
if PAYMENTS_MODULE_ENABLED:
    INSTALLED_APPS.append('payments')
if STAFF_MODULE_ENABLED:
    INSTALLED_APPS.append('staff')
if COMMS_MODULE_ENABLED:
    INSTALLED_APPS.append('comms')
if COMPLIANCE_MODULE_ENABLED:
    INSTALLED_APPS.append('compliance')
if DOCUMENTS_MODULE_ENABLED:
    INSTALLED_APPS.append('documents')
if CRM_MODULE_ENABLED:
    INSTALLED_APPS.append('crm')

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "core.middleware_tenant.TenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "auditlog.middleware.AuditLogMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates", BASE_DIR / "templates/admin"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

import dj_database_url

# Use DATABASE_URL if available (Railway), otherwise use individual config values
DATABASE_URL = config('DATABASE_PUBLIC_URL', default=config('DATABASE_URL', default=None))

if DATABASE_URL:
    DATABASES = {
        'default': dj_database_url.parse(DATABASE_URL)
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": config('DB_NAME'),
            "USER": config('DB_USER'),
            "PASSWORD": config('DB_PASSWORD'),
            "HOST": config('DB_HOST'),
            "PORT": config('DB_PORT'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (uploads)
# On Railway, use a persistent volume mounted at /data/media.
# Locally, fall back to ./media in the project directory.
MEDIA_VOLUME_PATH = config('MEDIA_VOLUME_PATH', default='')
if MEDIA_VOLUME_PATH:
    MEDIA_ROOT = MEDIA_VOLUME_PATH
else:
    MEDIA_ROOT = BASE_DIR / 'media'
MEDIA_URL = '/media/'

# Whitenoise config
WHITENOISE_USE_FINDERS = True
WHITENOISE_AUTOREFRESH = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CORS settings for frontend
_cors_defaults = ','.join([
    'http://localhost:3000',
    'http://localhost:3001',
    'http://127.0.0.1:3000',
    'http://127.0.0.1:3001',
    'https://nbne-business.vercel.app',
    'https://nbne-business-nbne.vercel.app',
    'https://nbne-business-restaurant-x.vercel.app',
    'https://nbne-business-health-club-x.vercel.app',
    'https://salon-x2.vercel.app',
    'https://fithub-lake.vercel.app',
    'https://tavola-gray.vercel.app',
    'https://app.nbnesigns.co.uk',
    'https://business.nbne.uk',
    'https://nbne-landing.vercel.app',
])
CORS_ALLOWED_ORIGINS = config('CORS_ALLOWED_ORIGINS', default=_cors_defaults).split(',')

CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_METHODS = ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']

# CSRF trusted origins for admin
_csrf_default = 'https://nbneplatform-production.up.railway.app'
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default=_csrf_default).split(',')

# Email configuration
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.ionos.co.uk')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@example.com')
EMAIL_SUBJECT_PREFIX = config('EMAIL_SUBJECT_PREFIX', default='[NBNE] ')
EMAIL_BRAND_NAME = config('EMAIL_BRAND_NAME', default='NBNE Business Platform')
EMAIL_TIMEOUT = 5  # 5 second timeout

# Resend HTTP API (Railway blocks SMTP, Resend is free)
RESEND_API_KEY = config('RESEND_API_KEY', default='')
RESEND_FROM_EMAIL = config('RESEND_FROM_EMAIL', default='onboarding@resend.dev')

# Booking reminder email (separate SMTP credentials via IONOS)
REMINDER_EMAIL_HOST = config('REMINDER_EMAIL_HOST', default='smtp.ionos.co.uk')
REMINDER_EMAIL_PORT = config('REMINDER_EMAIL_PORT', default=465, cast=int)
REMINDER_EMAIL_USE_SSL = config('REMINDER_EMAIL_USE_SSL', default=True, cast=bool)
REMINDER_EMAIL_HOST_USER = config('REMINDER_EMAIL_HOST_USER', default='')
REMINDER_EMAIL_HOST_PASSWORD = config('REMINDER_EMAIL_HOST_PASSWORD', default='')
REMINDER_FROM_EMAIL = config('REMINDER_FROM_EMAIL', default='')
REMINDER_INTERVAL_MINUTES = config('REMINDER_INTERVAL_MINUTES', default=10, cast=int)

# Stripe payments
STRIPE_SECRET_KEY = config('STRIPE_SECRET_KEY', default='')
STRIPE_WEBHOOK_SECRET = config('STRIPE_WEBHOOK_SECRET', default='')
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:3000')

# REST Framework
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
}

# Simple JWT
from datetime import timedelta
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=8),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}

# Jazzmin admin theme
from .jazzmin_settings import JAZZMIN_SETTINGS, JAZZMIN_UI_TWEAKS
