import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('icon', models.CharField(blank=True, default='', help_text='Emoji or icon name', max_length=50)),
                ('data_origin', models.CharField(choices=[('REAL', 'Real'), ('DEMO', 'Demo')], db_index=True, default='REAL', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_categories', to='tenants.tenantsettings')),
            ],
            options={
                'verbose_name_plural': 'Menu categories',
                'ordering': ['sort_order', 'name'],
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='', help_text='Short description shown on menu')),
                ('price_pence', models.IntegerField(help_text='Price in pence', validators=[django.core.validators.MinValueValidator(0)])),
                ('image_url', models.URLField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('sold_out', models.BooleanField(default=False, help_text='Temporarily unavailable')),
                ('prep_time_minutes', models.IntegerField(default=10, help_text='Estimated prep time in minutes')),
                ('vegetarian', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('gluten_free', models.BooleanField(default=False)),
                ('total_ordered', models.IntegerField(default=0)),
                ('total_revenue_pence', models.IntegerField(default=0)),
                ('data_origin', models.CharField(choices=[('REAL', 'Real'), ('DEMO', 'Demo')], db_index=True, default='REAL', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.menucategory')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='tenants.tenantsettings')),
            ],
            options={
                'ordering': ['category__sort_order', 'sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_ref', models.CharField(db_index=True, max_length=10)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_phone', models.CharField(blank=True, default='', max_length=50)),
                ('customer_email', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('received', 'Received'), ('preparing', 'Preparing'), ('ready', 'Ready for Collection'), ('collected', 'Collected'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('source', models.CharField(choices=[('online', 'Online Order'), ('phone', 'Phone Order'), ('walkin', 'Walk-in')], default='online', max_length=10)),
                ('payment_method', models.CharField(choices=[('card', 'Card (Stripe)'), ('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('unpaid', 'Not Yet Paid')], default='unpaid', max_length=20)),
                ('payment_confirmed', models.BooleanField(default=False)),
                ('stripe_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('subtotal_pence', models.IntegerField(default=0)),
                ('total_pence', models.IntegerField(default=0)),
                ('estimated_ready_minutes', models.IntegerField(default=0, help_text='Estimated minutes until ready')),
                ('estimated_ready_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='', help_text='Special instructions from customer')),
                ('kitchen_notes', models.TextField(blank=True, default='', help_text='Internal notes for kitchen')),
                ('placed_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, help_text='When kitchen started preparing', null=True)),
                ('ready_at', models.DateTimeField(blank=True, help_text='When marked as ready', null=True)),
                ('collected_at', models.DateTimeField(blank=True, help_text='When customer collected', null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('data_origin', models.CharField(choices=[('REAL', 'Real'), ('DEMO', 'Demo')], db_index=True, default='REAL', max_length=4)),
                ('demo_seed_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='tenants.tenantsettings')),
            ],
            options={
                'ordering': ['-placed_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Snapshot of item name at time of order', max_length=200)),
                ('quantity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price_pence', models.IntegerField(help_text='Snapshot of price at time of order')),
                ('notes', models.CharField(blank=True, default='', help_text='Item-level special requests', max_length=500)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='orders.menuitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderQueueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_wait_minutes', models.IntegerField(default=15)),
                ('auto_calculate_wait', models.BooleanField(default=True, help_text='Auto-calculate from queue depth')),
                ('avg_prep_time_minutes', models.IntegerField(default=12, help_text='Average prep time per order')),
                ('max_concurrent_orders', models.IntegerField(default=5, help_text='How many orders kitchen can handle at once')),
                ('accepting_orders', models.BooleanField(default=True)),
                ('not_accepting_reason', models.CharField(blank=True, default='', max_length=200)),
                ('opening_time', models.TimeField(blank=True, null=True)),
                ('closing_time', models.TimeField(blank=True, null=True)),
                ('seasonal_closed', models.BooleanField(default=False, help_text='Closed for the season')),
                ('seasonal_message', models.CharField(blank=True, default='', max_length=500)),
                ('bank_transfer_details', models.TextField(blank=True, default='', help_text='Bank name, sort code, account number')),
                ('accept_card', models.BooleanField(default=True)),
                ('accept_cash', models.BooleanField(default=True)),
                ('accept_bank_transfer', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order_queue_settings', to='tenants.tenantsettings')),
            ],
            options={
                'verbose_name': 'Order Queue Settings',
                'verbose_name_plural': 'Order Queue Settings',
            },
        ),
        migrations.CreateModel(
            name='DailyOrderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue_pence', models.IntegerField(default=0)),
                ('total_items_sold', models.IntegerField(default=0)),
                ('avg_order_value_pence', models.IntegerField(default=0)),
                ('peak_hour', models.IntegerField(blank=True, help_text='Hour with most orders (0-23)', null=True)),
                ('cancelled_orders', models.IntegerField(default=0)),
                ('avg_wait_minutes', models.FloatField(default=0)),
                ('weather_temp_c', models.FloatField(blank=True, null=True)),
                ('weather_condition', models.CharField(blank=True, default='', max_length=50)),
                ('is_school_holiday', models.BooleanField(default=False)),
                ('is_bank_holiday', models.BooleanField(default=False)),
                ('is_weekend', models.BooleanField(default=False)),
                ('holiday_name', models.CharField(blank=True, default='', max_length=100)),
                ('day_of_week', models.IntegerField(default=0)),
                ('week_number', models.IntegerField(default=0)),
                ('data_origin', models.CharField(choices=[('REAL', 'Real'), ('DEMO', 'Demo')], db_index=True, default='REAL', max_length=4)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_order_summaries', to='tenants.tenantsettings')),
            ],
            options={
                'verbose_name_plural': 'Daily order summaries',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ItemDailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('quantity_sold', models.IntegerField(default=0)),
                ('revenue_pence', models.IntegerField(default=0)),
                ('is_school_holiday', models.BooleanField(default=False)),
                ('is_bank_holiday', models.BooleanField(default=False)),
                ('is_weekend', models.BooleanField(default=False)),
                ('day_of_week', models.IntegerField(default=0)),
                ('week_number', models.IntegerField(default=0)),
                ('data_origin', models.CharField(choices=[('REAL', 'Real'), ('DEMO', 'Demo')], db_index=True, default='REAL', max_length=4)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_sales', to='orders.menuitem')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_daily_sales', to='tenants.tenantsettings')),
            ],
            options={
                'verbose_name_plural': 'Item daily sales',
                'ordering': ['-date'],
                'unique_together': {('tenant', 'menu_item', 'date')},
            },
        ),
    ]
