from django.urls import path
from . import views

urlpatterns = [
    path('', views.staff_list, name='staff_list'),
    path('create/', views.staff_create, name='staff_create'),
    path('<int:staff_id>/', views.staff_detail, name='staff_detail'),
    path('<int:staff_id>/update/', views.staff_update, name='staff_update'),
    path('<int:staff_id>/delete/', views.staff_delete, name='staff_delete'),
    path('purge/', views.staff_purge, name='staff_purge'),
    path('my-shifts/', views.my_shifts, name='my_shifts'),
    path('shifts/', views.shift_list, name='shift_list'),
    path('shifts/create/', views.shift_create, name='shift_create'),
    path('shifts/<int:shift_id>/update/', views.shift_update, name='shift_update'),
    path('shifts/<int:shift_id>/delete/', views.shift_delete, name='shift_delete'),
    path('leave/', views.leave_list, name='leave_list'),
    path('leave/calendar/', views.leave_calendar, name='leave_calendar'),
    path('leave/create/', views.leave_create, name='leave_create'),
    path('leave/<int:leave_id>/review/', views.leave_review, name='leave_review'),
    path('leave/<int:leave_id>/delete/', views.leave_delete, name='leave_delete'),
    path('training/', views.training_list, name='training_list'),
    path('training/create/', views.training_create, name='training_create'),
    path('training/<int:record_id>/delete/', views.training_delete, name='training_delete'),
    path('training/reminders/', views.training_reminders, name='training_reminders'),
    path('training/compliance/', views.training_compliance, name='training_compliance'),
    path('training/courses/', views.training_course_list, name='training_course_list'),
    path('training/courses/create/', views.training_course_create, name='training_course_create'),
    path('training/courses/<int:course_id>/update/', views.training_course_update, name='training_course_update'),
    path('training/courses/<int:course_id>/delete/', views.training_course_delete, name='training_course_delete'),
    path('absence/', views.absence_list, name='absence_list'),
    path('absence/create/', views.absence_create, name='absence_create'),
    # Working Hours
    path('working-hours/', views.working_hours_list, name='working_hours_list'),
    path('working-hours/create/', views.working_hours_create, name='working_hours_create'),
    path('working-hours/<int:wh_id>/update/', views.working_hours_update, name='working_hours_update'),
    path('working-hours/<int:wh_id>/delete/', views.working_hours_delete, name='working_hours_delete'),
    path('working-hours/bulk-set/', views.working_hours_bulk_set, name='working_hours_bulk_set'),
    # Timesheets
    path('timesheets/', views.timesheet_list, name='timesheet_list'),
    path('timesheets/<int:ts_id>/update/', views.timesheet_update, name='timesheet_update'),
    path('timesheets/generate/', views.timesheet_generate, name='timesheet_generate'),
    path('timesheets/summary/', views.timesheet_summary, name='timesheet_summary'),
    path('timesheets/export/', views.timesheet_export_csv, name='timesheet_export_csv'),
    # Project Codes
    path('project-codes/', views.project_code_list, name='project_code_list'),
    path('project-codes/create/', views.project_code_create, name='project_code_create'),
    path('project-codes/<int:pc_id>/update/', views.project_code_update, name='project_code_update'),
    path('project-codes/<int:pc_id>/delete/', views.project_code_delete, name='project_code_delete'),
    # Payroll
    path('payroll/summary/', views.payroll_summary, name='payroll_summary'),
]
