#!/bin/bash
# Spin up a new client instance
# Usage: ./new-client.sh <slug> <domain> <frontend-port> <backend-port>
# Example: ./new-client.sh ne-fire-medical nefireandmedical.co.uk 3006 8006

set -euo pipefail

SLUG="${1:?Usage: $0 <slug> <domain> <fe-port> <be-port>}"
DOMAIN="${2:?Usage: $0 <slug> <domain> <fe-port> <be-port>}"
FE_PORT="${3:?Usage: $0 <slug> <domain> <fe-port> <be-port>}"
BE_PORT="${4:?Usage: $0 <slug> <domain> <fe-port> <be-port>}"

BASE_DIR="/opt/nbne"
INSTANCE_DIR="$BASE_DIR/instances/$SLUG"

if [ -d "$INSTANCE_DIR" ]; then
  echo "❌ Instance $SLUG already exists at $INSTANCE_DIR"
  exit 1
fi

echo "🔧 Creating instance: $SLUG ($DOMAIN)"
mkdir -p "$INSTANCE_DIR"

# Generate secrets
DB_PASS=$(openssl rand -hex 16)
SECRET=$(openssl rand -hex 32)

# Create .env file
cat > "$INSTANCE_DIR/.env" <<EOF
# Client: $SLUG
# Domain: $DOMAIN
# Created: $(date -u +%Y-%m-%dT%H:%M:%SZ)

CLIENT_SLUG=$SLUG
DOMAIN=$DOMAIN
FRONTEND_PORT=$FE_PORT
BACKEND_PORT=$BE_PORT

# Database
DB_PASSWORD=$DB_PASS

# Django
SECRET_KEY=$SECRET

# Email (IONOS SMTP — update per client if needed)
EMAIL_USER=toby@nbnesigns.com
EMAIL_PASSWORD=
REMINDER_EMAIL_USER=toby@nbnesigns.com
REMINDER_EMAIL_PASSWORD=
REMINDER_FROM_EMAIL=toby@nbnesigns.com

# R2 media storage (shared Cloudflare bucket)
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=
R2_ENDPOINT_URL=https://5551fa1ba3cec479fd938b41b642e9.r2.cloudflarestorage.com
R2_PUBLIC_URL=https://pub-0a37d1fed9c043aab8f7180d8b112489.r2.dev

# Stripe (per-client — set up when ready)
STRIPE_SECRET_KEY=
STRIPE_WEBHOOK_SECRET=

# OpenAI
OPENAI_API_KEY=

# Resend (fallback email API)
RESEND_API_KEY=
RESEND_FROM_EMAIL=onboarding@resend.dev
EOF

echo "📝 Created .env at $INSTANCE_DIR/.env"
echo "⚠️  Remember to fill in sensitive values (EMAIL_PASSWORD, R2 keys, Stripe, OpenAI)"

# Generate Nginx config
NGINX_CONF="/etc/nginx/sites-enabled/$SLUG.conf"
cat > "$NGINX_CONF" <<NGINX
# $SLUG — $DOMAIN
# Auto-generated by new-client.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    ssl_certificate     /etc/ssl/cloudflare/origin.pem;
    ssl_certificate_key /etc/ssl/cloudflare/origin-key.pem;

    client_max_body_size 50M;

    # Django admin static files
    location /static/ {
        proxy_pass http://127.0.0.1:$BE_PORT;
        proxy_set_header Host \$host;
    }

    # API → Django backend
    location /api/ {
        proxy_pass http://127.0.0.1:$BE_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header X-Tenant-Slug $SLUG;
    }

    # Django admin panel
    location /admin/ {
        proxy_pass http://127.0.0.1:$BE_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Media files → R2 public URL
    location /media/ {
        proxy_pass https://pub-0a37d1fed9c043aab8f7180d8b112489.r2.dev/;
    }

    # Everything else → Next.js frontend
    location / {
        proxy_pass http://127.0.0.1:$FE_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}

# HTTP → HTTPS redirect
server {
    listen 80;
    server_name $DOMAIN;
    return 301 https://\$host\$request_uri;
}
NGINX

echo "📝 Created Nginx config at $NGINX_CONF"

# Test and reload Nginx
nginx -t && systemctl reload nginx
echo "✅ Nginx reloaded"

# Start the instance
cd "$INSTANCE_DIR"
docker compose --env-file .env \
  -f "$BASE_DIR/shared/docker/docker-compose.client.yml" \
  -p "$SLUG" \
  up -d --build

echo ""
echo "═══════════════════════════════════════════════"
echo "✅ Client $SLUG is live!"
echo "   Domain:   https://$DOMAIN"
echo "   Frontend: http://127.0.0.1:$FE_PORT"
echo "   Backend:  http://127.0.0.1:$BE_PORT"
echo ""
echo "   Next steps:"
echo "   1. Point $DOMAIN DNS to this server (A record → $(curl -s ifconfig.me))"
echo "   2. Enable Cloudflare proxy (orange cloud) for SSL"
echo "   3. Fill in .env secrets and restart: docker compose -p $SLUG restart"
echo "═══════════════════════════════════════════════"
