# Generated by Django 4.2.9 on 2026-02-27 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_crm_sorted_upgrade"),
    ]

    operations = [
        migrations.CreateModel(
            name="LeadMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("email_in", "Email Received"),
                            ("email_out", "Email Sent"),
                            ("call", "Phone Call"),
                            ("sms", "SMS"),
                            ("note", "Note"),
                        ],
                        default="note",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=500)),
                ("body", models.TextField()),
                ("created_by", models.CharField(blank=True, max_length=200)),
                (
                    "ai_parsed",
                    models.JSONField(
                        blank=True,
                        help_text="AI-extracted fields from email",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="crm.lead",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
