# Generated by Django 4.2.9 on 2026-02-16 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("staff", "0004_backfill_tenant_nonnull"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Short code e.g. PROJ-001, OVERHEAD", max_length=30
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text='Descriptive name e.g. "Smith Kitchen Refit"',
                        max_length=255,
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Optional client name",
                        max_length=255,
                    ),
                ),
                (
                    "is_billable",
                    models.BooleanField(
                        default=True, help_text="Whether hours are billable to a client"
                    ),
                ),
                (
                    "hourly_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Default hourly rate for invoicing",
                        max_digits=8,
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_codes",
                        to="tenants.tenantsettings",
                    ),
                ),
            ],
            options={
                "db_table": "staff_project_code",
                "ordering": ["code"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.AddField(
            model_name="timesheetentry",
            name="project_code",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional project/job code for invoicing",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="timesheet_entries",
                to="staff.projectcode",
            ),
        ),
    ]
