# Generated by Django 4.2.9 on 2026-02-17 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_tenantsettings_enabled_modules_tenantsettings_slug"),
        ("staff", "0005_projectcode_timesheetentry_project_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainingCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="e.g. Manual Handling, First Aid", max_length=255
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Default training provider",
                        max_length=255,
                    ),
                ),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False, help_text="If true, all staff must complete this"
                    ),
                ),
                (
                    "renewal_months",
                    models.PositiveIntegerField(
                        default=12,
                        help_text="How often this must be renewed (months). 0 = no renewal.",
                    ),
                ),
                (
                    "reminder_days_before",
                    models.PositiveIntegerField(
                        default=30, help_text="Days before expiry to show a reminder"
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="training_courses",
                        to="tenants.tenantsettings",
                    ),
                ),
            ],
            options={
                "db_table": "staff_training_course",
                "ordering": ["-is_mandatory", "name"],
                "unique_together": {("tenant", "name")},
            },
        ),
        migrations.AddField(
            model_name="trainingrecord",
            name="course",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="records",
                to="staff.trainingcourse",
            ),
        ),
    ]
