# Generated by Django 4.2.9 on 2026-02-15 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0002_add_password_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("STAFF_SICK", "Staff Sick"),
                            ("COVER_REQUESTED", "Cover Requested"),
                            ("COVER_ACCEPTED", "Cover Accepted"),
                            ("COVER_DECLINED", "Cover Declined"),
                            ("BOOKING_ASSIGNED", "Booking Assigned"),
                            ("BOOKING_CANCELLED", "Booking Cancelled"),
                            ("BOOKING_RESCHEDULED", "Booking Rescheduled"),
                            ("PAYMENT_REQUESTED", "Payment Requested"),
                            ("PAYMENT_MARKED", "Payment Marked"),
                            ("COMPLIANCE_COMPLETED", "Compliance Completed"),
                            ("INCIDENT_RESOLVED", "Incident Resolved"),
                            ("LEAVE_APPROVED", "Leave Approved"),
                            ("LEAVE_DECLINED", "Leave Declined"),
                            ("OWNER_OVERRIDE", "Owner Override"),
                            ("ASSISTANT_COMMAND", "Assistant Command"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                (
                    "source_event_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="The operational event type that triggered this action (e.g. staff_sick)",
                        max_length=50,
                    ),
                ),
                (
                    "source_entity_type",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("source_entity_id", models.IntegerField(blank=True, null=True)),
                (
                    "action_label",
                    models.CharField(
                        help_text='The action label clicked by the owner (e.g. "Ask Jordan to cover")',
                        max_length=255,
                    ),
                ),
                (
                    "action_detail",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Additional context about the action taken",
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Structured data: entities, parameters, assistant parse result, etc.",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="business_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Business Event",
                "verbose_name_plural": "Business Events",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="core_busine_event_t_ca53f9_idx",
                    ),
                    models.Index(
                        fields=["source_entity_type", "source_entity_id"],
                        name="core_busine_source__36e70f_idx",
                    ),
                ],
            },
        ),
    ]
